[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "coop_rl"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pyarrow",
    "numpy",
    "pandas",
    "gymnasium",
    "matplotlib",
    "seaborn",
    "ipykernel",
    "ipywidgets",
]

[project.optional-dependencies]
ml-cpu = [
  "jax[cpu]",
  "tensorflow",
  "tensorflow-probability",
  "tensorflow-datasets",
  "optax",
  "flax",
  "clu",
  "ml-collections",
  "ray[default]",
]

[tool.setuptools.packages.find]
include = ["coop_rl"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
